name: Continuous integration

on:
  pull_request:
    branches:
      - '**'
  push:
    branches: [ master ]
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Cache node modules
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install, lint and build
        run: |
          npm ci
          npm run lint:no-fix
          npm run build
        env:
          CI: ${{ true }}
      - name: Docker meta
        id: docker_meta
        if: "contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'"
        uses: docker/metadata-action@v3.5.0
        with:
          # list of Docker images to use as base name for tags
          images: c2corg/c2c_ui
      - name: Login to DockerHub
        if: "contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        if: "contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Get the branch
        id: get_branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}
      - name: Create clean branch name
        id: clean_branch
        run: echo ::set-output name=CLEAN_BRANCH::${BRANCH/\//-}
        env:
          BRANCH: ${{ steps.get_branch.outputs.BRANCH }}
      - name: Build for github pages
        run: npm run build:github
        env:
          GITHUB_PAGES_BRANCH: ${{ steps.clean_branch.outputs.CLEAN_BRANCH }}
      - name: Upload artifact for github pages
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: dist/*

  github-pages:
    needs: build
    if: "!contains(github.ref, 'refs/heads/dependabot')"
    runs-on: ubuntu-latest
    concurrency: github-pages
    steps:
      - name: Get the branch
        id: get_branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}
      - name: Create clean branch name
        id: clean_branch
        run: echo ::set-output name=CLEAN_BRANCH::${BRANCH/\//-}
        env:
          BRANCH: ${{ steps.get_branch.outputs.BRANCH }}
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          ref: gh-pages
      - name: Remove current branch files
        run: rm -rf ${{ steps.clean_branch.outputs.CLEAN_BRANCH }}
      - name: Retrieve github pages artifact
        uses: actions/download-artifact@v2
        with:
          name: github-pages
          path: ${{ steps.clean_branch.outputs.CLEAN_BRANCH }}
      - name: Commit files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Deploy ${{ steps.get_branch.outputs.BRANCH }} branch"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

  create-release:
    needs: build
    if: "contains(github.ref, 'refs/tags/v')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Generate changelog for release
        id: release_changelog
        run: |
          previousTag=$(git tag | sort -V -r | head -2 | awk '{split($0, tags, "\n")} END {print tags[1]}')
          currentTag=$(git tag | sort -V -r | head -1)
          changelog=$(git log --pretty=oneline ${previousTag}..${currentTag} --no-merges)
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"
      - name: Create or update release
        uses: meeDamian/github-release@2.0
        with:
          body: ${{ steps.release_changelog.outputs.changelog }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true

  push-i18n:
    needs: build
    if: "github.ref == 'refs/heads/master' && github.repository == 'c2corg/c2c_ui'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Push translations to Transifex
        run: |
          echo "::add-mask::$TOKEN"
          npm i
          npm run messages:extract
          curl --location --fail --request POST 'https://rest.api.transifex.com/resource_strings_async_uploads' --header 'Content-Type: multipart/form-data' --header "Authorization: Bearer $TOKEN" --form 'content=@"src/translations/c2corg_ui-client.pot"' --form 'resource="o:camptocamp-association:p:c2corg_ui:r:main"'
        env:
          TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
